# Generated by Django 4.1.7 on 2023-04-06 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_questions_rename_first_name_signup_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='question_Number',
        ),
    ]
