# Generated by Django 4.1.7 on 2023-04-06 12:36

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_questions_question_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
                ('custom_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
