# Generated by Django 4.1.7 on 2023-04-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_questions_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='questions',
            managers=[
            ],
        ),
    ]
