# Generated by Django 4.1.7 on 2023-05-25 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterData',
            fields=[
                ('cluster_number', models.AutoField(primary_key=True, serialize=False)),
                ('cluster_line', models.TextField()),
                ('cluster_mark', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.questions')),
            ],
        ),
    ]
