# Generated by Django 4.1.7 on 2023-05-29 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_clusterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clusterNo', models.TextField()),
                ('clusterLines', models.TextField()),
                ('cluster_mark', models.TextField()),
            ],
        ),
    ]
