# Generated by Django 4.1.7 on 2023-06-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_formdata_clusters'),
    ]

    operations = [
        migrations.CreateModel(
            name='FData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('total_mark', models.IntegerField()),
            ],
        ),
    ]
