# Generated by Django 4.1.7 on 2023-06-19 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_alter_score_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='score',
            name='user',
        ),
    ]
