# Generated by Django 4.1.7 on 2023-06-19 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_score_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='scoreOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('teacher_answer', models.TextField()),
                ('teacher_mark', models.IntegerField()),
                ('student_answer', models.TextField()),
                ('student_mark', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
