# Generated by Django 4.1.7 on 2023-06-19 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_scoreone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='score',
        ),
    ]
