# Generated by Django 4.1.7 on 2023-07-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='fdata',
            name='teacher_clusters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
