# Generated by Django 4.1.7 on 2023-07-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_scoreone_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreone',
            name='question',
            field=models.CharField(max_length=5000),
        ),
    ]
