# Generated by Django 4.1.7 on 2023-07-18 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_scoreone_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FData',
        ),
        migrations.DeleteModel(
            name='scoreOne',
        ),
    ]
