# Generated by Django 4.1.7 on 2023-07-18 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_delete_fdata_delete_scoreone'),
    ]

    operations = [
        migrations.CreateModel(
            name='FData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('total_mark', models.IntegerField()),
                ('teacher_clusters', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='scoreOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=5000)),
                ('teacher_answer', models.TextField()),
                ('teacher_mark', models.IntegerField()),
                ('student_answer', models.TextField()),
                ('student_mark', models.IntegerField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
