# Generated by Django 4.1.7 on 2023-07-18 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_alter_scoreone_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreone',
            name='user',
        ),
    ]
