# Generated by Django 4.1.7 on 2023-07-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_scoreone_user'),
    ]

    operations = [
    ]
