# Generated by Django 4.1.7 on 2023-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0044_auto_20230718_2123'),
    ]

    operations = [
    ]
