# Generated by Django 4.1.7 on 2023-07-18 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20230718_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoreone',
            name='user',
        ),
    ]
